version: '3'

services:
    dev_env:
        image: ghcr.io/mitchellthompkins/consteig_dev_image:latest
        environment:
            - USER=${USER}
            - Display=${DISPLAY}
            - MY_UID=${MY_UID:? Error -> need UID.}
            - MY_GID=${MY_GID:? Error -> need GID.}
        volumes:
            - "${PWD}:${PWD}"
        network_mode: host
        tty: True
        working_dir: ${PWD}
        entrypoint: ${PWD}/entrypoint.sh
        command: /bin/bash

    dev_env_local_build:
        image: consteig_dev_image:latest
        environment:
            - USER=${USER}
            - Display=${DISPLAY}
            - MY_UID=${MY_UID:? Error -> need UID.}
            - MY_GID=${MY_GID:? Error -> need GID.}
        volumes:
            - "${PWD}:${PWD}"
        network_mode: host
        tty: True
        working_dir: ${PWD}
        entrypoint: ${PWD}/entrypoint.sh
        command: /bin/bash
