version: '3'

services:
    dev_env_local:
        image: ghcr.io/mitchellthompkins/consteig_dev_image:latest
        environment:
            - USER=${USER}
            - Display=${DISPLAY}
            - MY_UID=${MY_UID:? Error -> need UID.}
            - MY_GID=${MY_GID:? Error -> need GID.}
        volumes:
            - "${PWD}:${PWD}"
        network_mode: host
        tty: True
        working_dir: ${PWD}
        entrypoint: ${PWD}/local-entrypoint.sh
        command: /bin/bash

    dev_env_ci:
        image: ghcr.io/mitchellthompkins/consteig_dev_image:latest
        environment:
            - USER=${USER}
        volumes:
            - "${PWD}:${PWD}"
        network_mode: host
        tty: True
        working_dir: ${PWD}
        entrypoint: ${PWD}/ci-entrypoint.sh
        command: /bin/bash
