services:
    dev_env:
        image: ghcr.io/mitchellthompkins/consteig_dev_image:latest
        environment:
            - USER=${USER}
            - MY_UID=${MY_UID:? Error -> need UID.}
            - MY_GID=${MY_GID:? Error -> need GID.}
        volumes:
            - "${PWD}:${PWD}"
            - "${HOME}/.consteig_ash_history:/home/${USER}/.ash_history"
        network_mode: host
        tty: True
        working_dir: ${PWD}
        entrypoint: ${PWD}/entrypoint.sh
        command: /bin/sh
