# get the normalized current directory
THIS_DIR := $(shell pwd)

UID=$(shell id -u)
GID=$(shell id -g)

# Figure out where to build the software. Use BUILD_PREFIX if it was passed in.
BUILD_PREFIX ?= $(THIS_DIR)/build

BUILD_TOOL ?= make

BUILD_FILE = Makefile
CMAKE_GENERATOR = "Unix Makefiles"

JOB_FLAG := -j 4

INSTALL_PREFIX ?= $(shell echo $(THIS_DIR)/build )

# If CC/CXX are set, pass them to CMake
ifneq "$(CC)" ""
    CMAKE_OPTIONS += -DCMAKE_C_COMPILER=$(CC)
endif
ifneq "$(CXX)" ""
    CMAKE_OPTIONS += -DCMAKE_CXX_COMPILER=$(CXX)
endif

ifeq "$(CMAKE_OPTIONS)" ""
    CMAKE_OPTIONS := -G $(CMAKE_GENERATOR) -DCLANG_TIDY_FIX=$(CLANG_TIDY_FIX) -DCMAKE_INSTALL_PREFIX=$(INSTALL_PREFIX)
else
   # force cmake to be re-run if we change the cmake options
   $(shell rm -f $(BUILD_PREFIX)/$(BUILD_FILE))
endif

.PHONY: build
build: $(BUILD_PREFIX)/$(BUILD_FILE)
	@set -o xtrace; \
	export CTEST_OUTPUT_ON_FAILURE=1; \
	cmake --build $(BUILD_PREFIX) --target all -- $(JOB_FLAG) ${a}; \

.PHONY: help
help:
	@echo 'make [OPTIONS...] [TARGETS...]'
	@echo
	@echo 'TARGETS:'
	@echo
	@echo '<any>'
	@echo '    Any targets generated by CMake, e.g. all, test'
	@echo
	@echo 'remove'
	@echo '    delete the build directory'
	@echo
	@echo 'format'
	@echo '    runs clang-format on .h/.hpp and .c/.cpp files'
	@echo
	@echo 'test'
	@echo '    runs unit tests in parallel with ctest -j$$(getconf _NPROCESSORS_ONLN)'
	@echo
	@echo 'run-examples'
	@echo '    builds and runs all example executables'
	@echo
	@echo 'OPTIONS:'
	@echo
	@echo 'INSTALL_PREFIX=<path>'
	@echo '    Specifies the CMAKE_INSTALL_PREFIX CMake variable value'
	@echo '    default: ./build/
	@echo
	@echo '-j <jobs>'
	@echo '    <jobs> pass -j flag to underlying BUILD_TOOL to set the job number'
	@echo
	@echo 'CC=<compiler>'
	@echo '    C compiler to use (e.g. clang)'
	@echo
	@echo 'CXX=<compiler>'
	@echo '    C++ compiler to use (e.g. clang++)'

# Each generated test is its own executable, and ctest launches a separate
# process per test. On macOS, per-process launch overhead (~0.05s) dominates
# and causes ~800 tests to take ~1 minute sequentially. On Linux the same
# overhead is <0.01s per test. Running ctest in parallel hides this latency.
#
# The naive `cmake --build --target test` (used by the %: catch-all below)
# invokes ctest sequentially. The test binaries themselves run in 0ms on both
# platforms -- the entire difference is macOS costing ~0.05s per process
# launch vs <0.01s on Linux, multiplied across 800 tests.
#
# Example (macOS, single test via ctest):
#   time ctest -R generated_sym_6
#   Total Test time (real) = 0.02 sec
#   ctest -R generated_sym_6  0.03s user 0.01s system 85% cpu 0.049 total
#
# getconf _NPROCESSORS_ONLN is portable across macOS and Linux.
# Note: on macOS, the first `make test` after a build may be slow (~1-2s/test).
# Subsequent runs are fast (~0.1s/test). Root cause unknown. Suspected amfid/codesign
# verification overhead; tested by ad-hoc signing all binaries after build with:
#   find $(BUILD_PREFIX)/bin -type f -perm +111 -exec codesign --sign - --force {} \;
# but this had no effect.
.PHONY: test
test: $(BUILD_PREFIX)/$(BUILD_FILE)
	@set -o xtrace; \
	export CTEST_OUTPUT_ON_FAILURE=1; \
	ctest --test-dir $(BUILD_PREFIX) -j$$(getconf _NPROCESSORS_ONLN); \

.PHONY: format
format:
	find . \( -path "./test_dependencies/googletest" -o -path "./build" \) -prune -o -type f \( -name "*.hpp" -o -name "*.cpp" -o -name "*.h" -o -name "*.c" \) -print | xargs clang-format -i

.PHONY: check-format
check-format:
	find . \( -path "./test_dependencies/googletest" -o -path "./build" \) -prune -o -type f \( -name "*.hpp" -o -name "*.cpp" -o -name "*.h" -o -name "*.c" \) -print | xargs clang-format --dry-run --Werror

.PHONY: remove
remove:
	rm -rf build/

.PHONY: run-examples
run-examples:
	cmake -S . -B $(BUILD_PREFIX) $(CMAKE_OPTIONS) -DCONSTEIG_BUILD_TESTS=OFF
	@set -e; \
	cmake --build $(BUILD_PREFIX) --target examples -- $(JOB_FLAG); \
	for ex in matrix.main decomp.main eigen.main population.main butterworth.main; do \
		echo ""; \
		echo "========================================"; \
		echo "Running: $$ex"; \
		echo "========================================"; \
		$(BUILD_PREFIX)/bin/$$ex; \
	done

.PHONY: test-dc-motor-fail
test-dc-motor-fail:
	cmake -S . -B $(BUILD_PREFIX) $(CMAKE_OPTIONS) -DCONSTEIG_BUILD_TESTS=OFF
	@echo "========================================"; \
	echo "Building dc_motor_control.main (expected to fail)"; \
	echo "========================================"; \
	build_output=$$(cmake --build $(BUILD_PREFIX) --target dc_motor_control.main -- $(JOB_FLAG) 2>&1); \
	build_rc=$$?; \
	if [ $$build_rc -eq 0 ]; then \
		echo "ERROR: dc_motor_control.main built successfully but should have failed!"; \
		exit 1; \
	elif echo "$$build_output" | grep -q "static assertion failed\|static_assert failed"; then \
		echo ""; \
		echo "========================================"; \
		echo "Build failed as expected (static_assert rejected bad PID gains)"; \
		echo "========================================"; \
	else \
		echo "ERROR: Build failed but not due to expected static_assert:"; \
		echo "$$build_output"; \
		exit 1; \
	fi

.PHONY: generate-test-cases
generate-test-cases:
	octave octave/generate_test_cases.m

$(BUILD_PREFIX)/$(BUILD_FILE):
	# create the temporary build directory if needed
	mkdir -p $(BUILD_PREFIX)
	touch -c $@
	# run CMake to generate and configure the build scripts
	ln -sf $(BUILD_PREFIX)/compile_commands.json compile_commands.json && \
	cd $(BUILD_PREFIX) && \
	cmake .. $(CMAKE_OPTIONS); \

# Other (custom) targets are passed through to the cmake-generated $(BUILD_FILE)
# Note: when no targets are passed from the commanding the special variable $@
# is "Makefile" so we need to angle this odd case differently.
%: $(BUILD_PREFIX)/$(BUILD_FILE)
	@set -o xtrace; \
	export CTEST_OUTPUT_ON_FAILURE=1; \
	cmake --build $(BUILD_PREFIX) --target $@ -- $(JOB_FLAG) ${a}; \

# All the Makefiles read themselves get matched if a target exists for them, so
# they will get matched by a Match anything target %:. This target is here
# to prevent the %: Match-anything target from matching, and do nothing.
Makefile:
	;

.PHONY: cmd
cmd: $(BUILD_PREFIX)/$(BUILD_FILE)
	export CTEST_OUTPUT_ON_FAILURE=1; \
	cd $(BUILD_PREFIX); \
	${a};

.PHONY: container.build
container.build:
	docker build --file Dockerfile --tag consteig_dev_image .

.PHONY: container.pull
container.pull:
	docker pull ghcr.io/mitchellthompkins/consteig_dev_image:latest

.PHONY: container.start
container.start:
	docker compose -f docker-compose.yml run --rm dev_env 'sh -x'

################################################################################
# Cross-compilation targets
################################################################################

# Build with ARM GCC cross-compiler (compile-only — static_assert is the test)
.PHONY: cross.arm-gcc
cross.arm-gcc:
	mkdir -p $(BUILD_PREFIX)-arm-gcc
	cd $(BUILD_PREFIX)-arm-gcc && \
	cmake .. -G $(CMAKE_GENERATOR) \
		-DCMAKE_TOOLCHAIN_FILE=$(THIS_DIR)/cmake/toolchains/arm-none-eabi-gcc.cmake \
		-DCONSTEIG_COMPILE_ONLY=ON
	cmake --build $(BUILD_PREFIX)-arm-gcc --target all -- $(JOB_FLAG)

# Build with ARM Clang cross-compiler (compile-only — static_assert is the test)
.PHONY: cross.arm-clang
cross.arm-clang:
	mkdir -p $(BUILD_PREFIX)-arm-clang
	cd $(BUILD_PREFIX)-arm-clang && \
	cmake .. -G $(CMAKE_GENERATOR) \
		-DCMAKE_TOOLCHAIN_FILE=$(THIS_DIR)/cmake/toolchains/arm-none-eabi-clang.cmake \
		-DCONSTEIG_COMPILE_ONLY=ON
	cmake --build $(BUILD_PREFIX)-arm-clang --target all -- $(JOB_FLAG)

# Build with all cross-compilers
.PHONY: cross
cross: cross.arm-gcc cross.arm-clang

container.make.%:
	docker compose -f docker-compose.yml run --rm dev_env 'make CC=$(CC) CXX=$(CXX) $*'
