# get the normalized current directory
THIS_DIR := $(shell pwd)

UID=$(shell id -u)
GID=$(shell id -g)

# Figure out where to build the software. Use BUILD_PREFIX if it was passed in.
BUILD_PREFIX ?= $(THIS_DIR)/build

BUILD_TOOL ?= make

BUILD_FILE = Makefile
CMAKE_GENERATOR = "Unix Makefiles"

JOB_FLAG := -j 4

INSTALL_PREFIX ?= $(shell echo $(THIS_DIR)/build )

RAISE_COMPILER_LIMITS ?= 1
ifeq "$(RAISE_COMPILER_LIMITS)" "1"
    CMAKE_OPTIONS += -DCONSTEIG_RAISE_COMPILER_LIMITS=ON
endif

# If CC/CXX are set, pass them to CMake
ifneq "$(CC)" ""
    CMAKE_OPTIONS += -DCMAKE_C_COMPILER=$(CC)
endif
ifneq "$(CXX)" ""
    CMAKE_OPTIONS += -DCMAKE_CXX_COMPILER=$(CXX)
endif

ifeq "$(CMAKE_OPTIONS)" ""
    CMAKE_OPTIONS := -G $(CMAKE_GENERATOR) -DCLANG_TIDY_FIX=$(CLANG_TIDY_FIX) -DCMAKE_INSTALL_PREFIX=$(INSTALL_PREFIX)
else
   # force cmake to be re-run if we change the cmake options
   $(shell rm -f $(BUILD_PREFIX)/$(BUILD_FILE))
endif

.PHONY: build
build: $(BUILD_PREFIX)/$(BUILD_FILE)
	@set -o xtrace; \
	export CTEST_OUTPUT_ON_FAILURE=1; \
	cmake --build $(BUILD_PREFIX) --target all -- $(JOB_FLAG) ${a}; \

.PHONY: h
h:
	@echo 'make [OPTIONS...] [TARGETS...]'
	@echo
	@echo 'TARGETS:'
	@echo
	@echo '<any>'
	@echo '    Any targets generated by CMake, e.g. all, test'
	@echo
	@echo 'remove'
	@echo '    delete the build directory'
	@echo
	@echo 'format'
	@echo '    runs clang-format on .h/.hpp and .c/.cpp files'
	@echo
	@echo 'test'
	@echo '    runs unit tests in parallel with ctest -j$$(getconf _NPROCESSORS_ONLN)'
	@echo
	@echo 'examples'
	@echo '    builds all example executables'
	@echo
	@echo 'OPTIONS:'
	@echo
	@echo 'INSTALL_PREFIX=<path>'
	@echo '    Specifies the CMAKE_INSTALL_PREFIX CMake variable value'
	@echo '    default: ./build/
	@echo
	@echo '-j <jobs>'
	@echo '    <jobs> pass -j flag to underlying BUILD_TOOL to set the job number'
	@echo
	@echo 'CC=<compiler>'
	@echo '    C compiler to use (e.g. clang)'
	@echo
	@echo 'CXX=<compiler>'
	@echo '    C++ compiler to use (e.g. clang++)'

# Each generated test is its own executable, and ctest launches a separate
# process per test. On macOS, per-process launch overhead (~0.05s) dominates
# and causes ~800 tests to take ~1 minute sequentially. On Linux the same
# overhead is <0.01s per test. Running ctest in parallel hides this latency.
#
# The naive `cmake --build --target test` (used by the %: catch-all below)
# invokes ctest sequentially. The test binaries themselves run in 0ms on both
# platforms -- the entire difference is macOS costing ~0.05s per process
# launch vs <0.01s on Linux, multiplied across 800 tests.
#
# Example (macOS, single test via ctest):
#   time ctest -R generated_sym_6
#   Total Test time (real) = 0.02 sec
#   ctest -R generated_sym_6  0.03s user 0.01s system 85% cpu 0.049 total
#
# getconf _NPROCESSORS_ONLN is portable across macOS and Linux.
.PHONY: test
test: $(BUILD_PREFIX)/$(BUILD_FILE)
	@set -o xtrace; \
	export CTEST_OUTPUT_ON_FAILURE=1; \
	ctest --test-dir $(BUILD_PREFIX) -j$$(getconf _NPROCESSORS_ONLN); \

.PHONY: format
format:
	find . \( -path "./test_dependencies/googletest" -o -path "./build" \) -prune -o -type f \( -name "*.hpp" -o -name "*.cpp" -o -name "*.h" -o -name "*.c" \) -print | xargs clang-format -i

.PHONY: check-format
check-format:
	find . \( -path "./test_dependencies/googletest" -o -path "./build" \) -prune -o -type f \( -name "*.hpp" -o -name "*.cpp" -o -name "*.h" -o -name "*.c" \) -print | xargs clang-format --dry-run --Werror

.PHONY: remove
remove:
	rm -rf build/

.PHONY: examples
examples: matrix.main decomp.main eigen.main population.main butterworth.main

.PHONY: generate-test-cases
generate-test-cases:
	octave octave/generate_test_cases.m

$(BUILD_PREFIX)/$(BUILD_FILE):
	# create the temporary build directory if needed
	mkdir -p $(BUILD_PREFIX)
	touch -c $@
	# run CMake to generate and configure the build scripts
	ln -sf $(BUILD_PREFIX)/compile_commands.json compile_commands.json && \
	git config core.hooksPath .githooks && \
	cd $(BUILD_PREFIX) && \
	cmake .. $(CMAKE_OPTIONS); \

# Other (custom) targets are passed through to the cmake-generated $(BUILD_FILE)
# Note: when no targets are passed from the commanding the special variable $@
# is "Makefile" so we need to angle this odd case differently.
%: $(BUILD_PREFIX)/$(BUILD_FILE)
	@set -o xtrace; \
	export CTEST_OUTPUT_ON_FAILURE=1; \
	cmake --build $(BUILD_PREFIX) --target $@ -- $(JOB_FLAG) ${a}; \

# All the Makefiles read themselves get matched if a target exists for them, so
# they will get matched by a Match anything target %:. This target is here
# to prevent the %: Match-anything target from matching, and do nothing.
Makefile:
	;

.PHONY: cmd
cmd: $(BUILD_PREFIX)/$(BUILD_FILE)
	export CTEST_OUTPUT_ON_FAILURE=1; \
	cd $(BUILD_PREFIX); \
	${a};

.PHONY: container.build
container.build:
	docker build --file Dockerfile --tag consteig_dev_image .

.PHONY: container.pull
container.pull:
	docker pull ghcr.io/mitchellthompkins/consteig_dev_image:latest

.PHONY: container.start
container.start:
	docker compose -f docker-compose.yml run --rm dev_env 'sh -x'

container.make.%:
	docker compose -f docker-compose.yml run --rm dev_env 'make $*'
