#include <gtest/gtest.h>

#include "char_poly_reference.hpp"
#include "operations.hpp"
#include "test_tools.hpp"

using namespace consteig;
using namespace char_poly_ref;

// Reference values generated by Octave's poly() function.
// See octave/generate_char_poly_tests.m for the generation script.

// 1x1

TEST(char_poly, scalar_1x1)
{
    static constexpr auto result = char_poly(mat_1x1);
    static_assert(result == poly_1x1, MSG);
    ASSERT_TRUE(result == poly_1x1);
}

// 2x2 diagonal

TEST(char_poly, diagonal_2x2_double)
{
    static constexpr auto result = char_poly(mat_2x2_diag);
    static_assert(result == poly_2x2_diag, MSG);
    ASSERT_TRUE(result == poly_2x2_diag);
}

TEST(char_poly, diagonal_2x2_float)
{
    static constexpr auto result = char_poly(mat_2x2_diag_f);
    static_assert(result == poly_2x2_diag_f, MSG);
    ASSERT_TRUE(result == poly_2x2_diag_f);
}

// 2x2 general

TEST(char_poly, general_2x2)
{
    static constexpr auto result = char_poly(mat_2x2_general);
    static_assert(
        equalWithinMat(result, poly_2x2_general, CONSTEIG_TEST_TOLERANCE), MSG);
    for (Size i = 0u; i < 3u; ++i)
    {
        EXPECT_NEAR(result(i, 0u), poly_2x2_general(i, 0u),
                    CONSTEIG_TEST_TOLERANCE);
    }
}

// 3x3 upper triangular

TEST(char_poly, upper_triangular_3x3)
{
    static constexpr auto result = char_poly(mat_3x3_upper_tri);
    static_assert(
        equalWithinMat(result, poly_3x3_upper_tri, CONSTEIG_TEST_TOLERANCE),
        MSG);
    for (Size i = 0u; i < 4u; ++i)
    {
        EXPECT_NEAR(result(i, 0u), poly_3x3_upper_tri(i, 0u),
                    CONSTEIG_TEST_TOLERANCE);
    }
}

// 3x3 general

TEST(char_poly, general_3x3)
{
    static constexpr auto result = char_poly(mat_3x3_general);
    static_assert(
        equalWithinMat(result, poly_3x3_general, CONSTEIG_TEST_TOLERANCE), MSG);
    for (Size i = 0u; i < 4u; ++i)
    {
        EXPECT_NEAR(result(i, 0u), poly_3x3_general(i, 0u),
                    CONSTEIG_TEST_TOLERANCE);
    }
}

// 4x4 diagonal

TEST(char_poly, diagonal_4x4)
{
    static constexpr auto result = char_poly(mat_4x4_diag);
    static_assert(
        equalWithinMat(result, poly_4x4_diag, CONSTEIG_TEST_TOLERANCE), MSG);
    for (Size i = 0u; i < 5u; ++i)
    {
        EXPECT_NEAR(result(i, 0u), poly_4x4_diag(i, 0u),
                    CONSTEIG_TEST_TOLERANCE);
    }
}

// 5x5 random

TEST(char_poly, random_5x5)
{
    static constexpr auto result = char_poly(mat_5x5_random);
    static_assert(
        equalWithinMat(result, poly_5x5_random, CONSTEIG_TEST_TOLERANCE), MSG);
    for (Size i = 0u; i < 6u; ++i)
    {
        EXPECT_NEAR(result(i, 0u), poly_5x5_random(i, 0u),
                    CONSTEIG_TEST_TOLERANCE);
    }
}

// 8x8 random

TEST(char_poly, random_8x8)
{
    static constexpr auto result = char_poly(mat_8x8_random);
    static_assert(
        equalWithinMat(result, poly_8x8_random, CONSTEIG_TEST_TOLERANCE), MSG);
    for (Size i = 0u; i < 9u; ++i)
    {
        EXPECT_NEAR(result(i, 0u), poly_8x8_random(i, 0u),
                    CONSTEIG_TEST_TOLERANCE);
    }
}

// 10x10 symmetric

TEST(char_poly, symmetric_10x10)
{
    static constexpr auto result = char_poly(mat_10x10_sym);
    static_assert(
        equalWithinMat(result, poly_10x10_sym, CONSTEIG_TEST_TOLERANCE), MSG);
    for (Size i = 0u; i < 11u; ++i)
    {
        EXPECT_NEAR(result(i, 0u), poly_10x10_sym(i, 0u),
                    CONSTEIG_TEST_TOLERANCE);
    }
}
