name: Docker Image CI

on:
  push:
    branches: [ mthompkins/add_docker ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
       docker build . --file Dockerfile --tag ghcr.io/mitchellthompkins/consteig_dev_image:latest
       docker run ghcr.io/mitchellthompkins/consteig_dev_image:latest
       docker push ghcr.io/mitchellthompkins/consteig_dev_image:latest
