name: Docker_Image_CI

on:
  push:
    branches: [ mthompkins/add_docker ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish the Docker image
    with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}
    run: |
            docker build . --file Dockerfile --tag ghcr.io/mitchellthompkins/consteig_dev_image:latest
            docker run ghcr.io/mitchellthompkins/consteig_dev_image:latest
            docker push ghcr.io/mitchellthompkins/consteig_dev_image:latest
