name: docker_image_ci

on:
  push:
    branches: [ mthompkins/add_docker ]
  pull_request:
    branches: [ develop ]

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Build and publish docker image
            run: |
                docker build . --file Dockerfile.local --tag consteig_local_dev_image:latest
                docker build . --file Dockerfile.ci --tag ghcr.io/mitchellthompkins/consteig_ci_dev_image:latest
                docker run ghcr.io/mitchellthompkins/consteig_ci_dev_image:latest
                docker push ghcr.io/mitchellthompkins/consteig_ci_dev_image:latest
