name: docker_image_ci

on:
  push:
  pull_request:
    branches:
        - develop

jobs:
    build_and_publish_container:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  context: .
            - name: Build and publish docker image
              run: |
                    docker build . --file Dockerfile --tag ghcr.io/mitchellthompkins/consteig_dev_image:latest
                    docker run ghcr.io/mitchellthompkins/consteig_dev_image:latest
                    docker push ghcr.io/mitchellthompkins/consteig_dev_image:latest

    build_and_test:
        needs: build_and_publish_container
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build tests
              run: |
                    export MY_UID=1000
                    export MY_GID=1000
                    git submodule update --init --recursive
                    make container.make.build
                    make container.make.test
