name: docker_image_ci

on:
  push:
    branches: [ mthompkins/add_docker ]
  pull_request:
    branches: [ develop ]

jobs:
    build_and_publish_container:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v1
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                context: .
          - name: Build and publish docker image
            run: |
                docker build . --file Dockerfile --tag ghcr.io/mitchellthompkins/consteig_ci_dev_image:latest
                docker run ghcr.io/mitchellthompkins/consteig_ci_dev_image:latest
                docker push ghcr.io/mitchellthompkins/consteig_ci_dev_image:latest

    build:
        needs: build_and_publish_container
        name: Build tests
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/mitchellthompkins/consteig_ci_dev_image:latest
            options: -v ${{ github.workspace }}:/work
            #volumes:
            #    - ${{ github.workspace }}:/workspace
        steps:
        #- run: docker run --rm -it -v $(pwd):$(pwd) -w $(pwd) consteig_local_dev_image make build
        - run: |
                ls -al
                cat readme.md
                make build
