name: docker_image_ci

on:
  push:
    branches: [ mthompkins/add_docker ]
  pull_request:
    branches: [ develop ]

jobs:
    build_and_publish_container:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  context: .
            - name: Build and publish docker image
              run: |
                  docker build . --file Dockerfile --tag ghcr.io/mitchellthompkins/consteig_dev_image:latest
                  docker run ghcr.io/mitchellthompkins/consteig_dev_image:latest
                  docker push ghcr.io/mitchellthompkins/consteig_dev_image:latest

    build:
        needs: build_and_publish_container
        runs-on: ubuntu-latest
        steps:
            - name: Build tests
              #working-directory: ${{ github.workspace }}
              run: |
                    cat ${{ github.workspace }}/readme.md
                    docker-compose -f docker-compose.yml run --rm dev_env 'make build'
                    docker-compose -f docker-compose.yml run --rm dev_env 'make test'
